# Generated by Django 5.2.1 on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="タイトル")),
                (
                    "use_case",
                    models.CharField(help_text="例: 画像生成, LP作成, SNS投稿", max_length=100, verbose_name="用途"),
                ),
                ("prompt_text", models.TextField(verbose_name="プロンプト本文")),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                ("tags", models.CharField(blank=True, help_text="カンマ区切りで入力", max_length=255, verbose_name="タグ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="prompts.category"),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
